version: "3.9"

services:
  manager:
    image: llagents/manager:local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PORT: "8080"
      ROOT_DOMAIN: llmagents.com
      USER_INSTANCE_IMAGE: llagents/user-instance:latest
      PROJECT_NETWORK_ID: runtime
    networks:
      - runtime
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any

networks:
  runtime:
    driver: overlay
    attachable: true
